# See https://cloud.google.com/sql/docs/mysql/connect-container-engine

apiVersion: v1
kind: Deployment
metadata:
  name: "example-deployment"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: web
          image: gcr.io/cashme-186014/kubernetes-example:1.1
          ports:
            - containerPort: 80
